# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(blank=True, max_length=300, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
    ]
