# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NasaDataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('collection_short_name', models.CharField(blank=True, max_length=300, null=True)),
                ('collection_long_name', models.CharField(blank=True, max_length=300, null=True)),
                ('hdf', models.FileField(blank=True, null=True, upload_to=b'')),
                ('xml', models.FileField(blank=True, null=True, upload_to=b'')),
                ('bounding_west', models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True)),
                ('bounding_north', models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True)),
                ('bounding_east', models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True)),
                ('bounding_south', models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
    ]
