# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasa', '0002_discretizeddatapoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discretizeddatapoint',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='discretizeddatapoint',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
