# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('text', models.CharField(max_length=256)),
                ('latitude', models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_tweet', models.BooleanField(default=False)),
                ('tweet_id', models.CharField(blank=True, max_length=128, null=True)),
                ('twitter_user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('twitter_user', models.CharField(blank=True, max_length=128, null=True)),
                ('language', models.CharField(blank=True, max_length=200, null=True)),
                ('sentiment', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='keyphrase',
            name='sentiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_phrases', to='sentiments.Sentiment'),
        ),
    ]
