# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment',
            name='is_tweet',
            field=models.BooleanField(default=False),
        ),
    ]
