# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentiments', '0002_sentiment_is_tweet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentiment',
            options={'ordering': ('created',)},
        ),
        migrations.RenameField(
            model_name='sentiment',
            old_name='date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='sentiment',
            old_name='twitter_id',
            new_name='tweet_id',
        ),
        migrations.RenameField(
            model_name='sentiment',
            old_name='twitter_name',
            new_name='twitter_user',
        ),
    ]
