# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentiments', '0003_auto_20160424_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='sentiment',
            name='language_iso',
        ),
        migrations.RemoveField(
            model_name='sentiment',
            name='language_score',
        ),
        migrations.AddField(
            model_name='sentiment',
            name='twitter_user_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='language',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='keyphrase',
            name='sentiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentiments.Sentiment'),
        ),
    ]
