# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiments', '0004_auto_20160424_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment',
            name='language',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
